ALTER TABLE companies
ADD COLUMN email VARCHAR(255) DEFAULT NULL,
ADD COLUMN phone VARCHAR(20) DEFAULT NULL,
ADD COLUMN zipcode VARCHAR(20) DEFAULT NULL,
ADD COLUMN street VARCHAR(255) DEFAULT NULL,
ADD COLUMN number VARCHAR(50) DEFAULT NULL,
ADD COLUMN complement VARCHAR(150) DEFAULT NULL,
ADD COLUMN neighborhood VARCHAR(100) DEFAULT NULL,
ADD COLUMN city VARCHAR(100) DEFAULT NULL,
ADD COLUMN state VARCHAR(50) DEFAULT NULL;
