CREATE TABLE IF NOT EXISTS measures (
    id INT PRIMARY KEY AUTO_INCREMENT,
    public_id VARCHAR(36) NOT NULL UNIQUE,
    company_id INT NOT NULL,
    name VARCHAR(100) NOT NULL,
    abbreviation VARCHAR(10) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE
);

ALTER TABLE products 
ADD COLUMN measure_id INT NULL,
ADD CONSTRAINT fk_product_measure FOREIGN KEY (measure_id) REFERENCES measures(id) ON DELETE SET NULL;
