/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Decimal = ColumnType<string, number | string>;

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface AccountingEntries {
  amount: Decimal;
  company_id: number;
  created_at: Generated<Date | null>;
  credit_account_id: number;
  debit_account_id: number;
  document_ref: Generated<string | null>;
  entry_date: Date;
  history: string;
  id: Generated<number>;
  public_id: string;
  status: Generated<"active" | "inactive">;
  updated_at: Generated<Date | null>;
}

export interface BankAccounts {
  account_number: Generated<string | null>;
  agency_number: Generated<string | null>;
  api_certificate: Generated<string | null>;
  api_client_id: Generated<string | null>;
  api_client_secret: Generated<string | null>;
  api_key: Generated<string | null>;
  company_id: number;
  created_at: Generated<Date | null>;
  current_balance: Generated<Decimal>;
  id: Generated<number>;
  initial_balance: Generated<Decimal>;
  institution: Generated<string | null>;
  name: string;
  public_id: string;
  type: Generated<"cash" | "checking" | "savings">;
  updated_at: Generated<Date | null>;
}

export interface BankStatements {
  amount: Decimal;
  bank_account_id: number;
  company_id: number;
  created_at: Generated<Date | null>;
  date: Date;
  description: string;
  id: Generated<number>;
  public_id: string;
  raw_data: Generated<string | null>;
  reconciled_transaction_id: Generated<number | null>;
  status: Generated<"ignored" | "pending" | "reconciled" | null>;
  transaction_id: Generated<string | null>;
  type: "expense" | "income";
  updated_at: Generated<Date | null>;
}

export interface Categories {
  company_id: number;
  created_at: Generated<Date | null>;
  id: Generated<number>;
  name: string;
  public_id: string;
  type: "expense" | "income";
  updated_at: Generated<Date | null>;
}

export interface ChartOfAccounts {
  code: string;
  company_id: number;
  created_at: Generated<Date | null>;
  easy_code: Generated<string | null>;
  id: Generated<number>;
  name: string;
  nature: Generated<"credit" | "debit">;
  public_id: string;
  status: Generated<"active" | "inactive">;
  type: Generated<"analytic" | "synthetic">;
  updated_at: Generated<Date | null>;
}

export interface Companies {
  allow_print_without_confirmation: Generated<number>;
  api_token: Generated<string | null>;
  certificate_expiration: Generated<Date | null>;
  certificate_name: Generated<string | null>;
  certificate_password: Generated<string | null>;
  certificate_url: Generated<string | null>;
  city: Generated<string | null>;
  /**
   * CNAE Principal
   */
  cnae_principal: Generated<string | null>;
  cnpj: Generated<string | null>;
  /**
   * Razão Social
   */
  company_name: Generated<string | null>;
  complement: Generated<string | null>;
  created_at: Generated<Date | null>;
  /**
   * 1=Simples Nacional, 2=Simples Nacional Excesso Rec. Bruta, 3=Regime Normal
   */
  crt: Generated<number | null>;
  /**
   * ID do CSC (NFCe)
   */
  csc_id: Generated<string | null>;
  /**
   * Token CSC (NFCe)
   */
  csc_token: Generated<string | null>;
  email: Generated<string | null>;
  id: Generated<number>;
  /**
   * Inscrição Estadual
   */
  ie: Generated<string | null>;
  /**
   * Inscrição Municipal
   */
  im: Generated<string | null>;
  is_active: Generated<number>;
  is_system: Generated<number>;
  neighborhood: Generated<string | null>;
  /**
   * Número da NFCe
   */
  nfce_number: Generated<number | null>;
  /**
   * Série da NFCe
   */
  nfce_series: Generated<number | null>;
  /**
   * 1=Produção, 2=Homologação
   */
  nfe_environment: Generated<number | null>;
  /**
   * Número da NFe
   */
  nfe_number: Generated<number | null>;
  /**
   * Série da NFe
   */
  nfe_series: Generated<number | null>;
  number: Generated<string | null>;
  phone: Generated<string | null>;
  /**
   * UUID for public reference
   */
  public_id: string;
  solidcon_api_token: Generated<string | null>;
  solidcon_url_1: Generated<string | null>;
  solidcon_url_2: Generated<string | null>;
  solidcon_url_3: Generated<string | null>;
  solidcon_url_4: Generated<string | null>;
  solidcon_url_5: Generated<string | null>;
  state: Generated<string | null>;
  street: Generated<string | null>;
  tax_regime: Generated<string | null>;
  /**
   * Nome Fantasia
   */
  trade_name: string;
  updated_at: Generated<Date | null>;
  whatsapp_business_scope: Generated<"company" | "user">;
  whatsapp_chat_provider: Generated<"business_qr">;
  zipcode: Generated<string | null>;
}

export interface Customers {
  certificate_expiration: Generated<Date | null>;
  certificate_password: Generated<string | null>;
  certificate_url: Generated<string | null>;
  city: Generated<string | null>;
  cnpj_cpf: Generated<string | null>;
  cnpj_document_url: Generated<string | null>;
  company_id: number;
  complement: Generated<string | null>;
  created_at: Generated<Date | null>;
  email: Generated<string | null>;
  id: Generated<number>;
  name: string;
  neighborhood: Generated<string | null>;
  number: Generated<string | null>;
  phone: Generated<string | null>;
  public_id: string;
  seller_user_id: Generated<number | null>;
  social_contract_url: Generated<string | null>;
  state: Generated<string | null>;
  street: Generated<string | null>;
  updated_at: Generated<Date | null>;
  zipcode: Generated<string | null>;
}

export interface IbgeCities {
  id: number;
  name: string;
  state_id: number;
}

export interface IbgeStates {
  id: number;
  name: string;
  region: "Centro-Oeste" | "Nordeste" | "Norte" | "Sudeste" | "Sul";
  uf: string;
}

export interface InventoryMovements {
  company_id: number;
  date: Generated<Date>;
  id: Generated<number>;
  product_id: number;
  purchase_id: Generated<number | null>;
  quantity: Decimal;
  sale_id: Generated<number | null>;
  type: "in" | "out";
}

export interface Manufacturers {
  cnpj: Generated<string | null>;
  company_id: number;
  created_at: Generated<Date | null>;
  email: Generated<string | null>;
  id: Generated<number>;
  name: string;
  phone: Generated<string | null>;
  public_id: string;
  updated_at: Generated<Date | null>;
}

export interface Measures {
  abbreviation: string;
  company_id: number;
  created_at: Generated<Date | null>;
  id: Generated<number>;
  name: string;
  public_id: string;
  updated_at: Generated<Date | null>;
}

export interface PriceTables {
  company_id: number;
  created_at: Generated<Date | null>;
  id: Generated<number>;
  markup_percentage: Generated<Decimal>;
  name: string;
  public_id: string;
  status: Generated<"active" | "inactive">;
  updated_at: Generated<Date | null>;
}

export interface ProductCategories {
  company_id: number;
  created_at: Generated<Date | null>;
  description: Generated<string | null>;
  id: Generated<number>;
  name: string;
  public_id: string;
  updated_at: Generated<Date | null>;
}

export interface Products {
  category_id: Generated<number | null>;
  cest: Generated<string | null>;
  company_id: number;
  cost_price: Generated<Decimal>;
  created_at: Generated<Date | null>;
  current_stock: Generated<Decimal>;
  description: Generated<string | null>;
  ean: Generated<string | null>;
  external_code: Generated<string | null>;
  id: Generated<number>;
  image_base64: Generated<string | null>;
  image_url: Generated<string | null>;
  manufacturer_id: Generated<number | null>;
  max_stock: Generated<number | null>;
  measure_id: Generated<number | null>;
  min_stock: Generated<number | null>;
  name: string;
  ncm: Generated<string | null>;
  public_id: string;
  selling_price: Generated<Decimal>;
  sku: Generated<string | null>;
  tax_rule_id: Generated<number | null>;
  updated_at: Generated<Date | null>;
}

export interface PurchaseItems {
  id: Generated<number>;
  product_id: number;
  purchase_id: number;
  quantity: Decimal;
  total_price: Decimal;
  unit_price: Decimal;
}

export interface PurchaseOrders {
  company_id: number;
  created_at: Generated<Date | null>;
  date: Date;
  id: Generated<number>;
  public_id: string;
  status: Generated<"cancelled" | "completed" | "pending">;
  supplier_id: number;
  total_amount: Generated<Decimal>;
  updated_at: Generated<Date | null>;
}

export interface RolePermissions {
  can_view: Generated<number | null>;
  company_id: number;
  created_at: Generated<Date | null>;
  id: Generated<number>;
  module: string;
  role: string;
  updated_at: Generated<Date | null>;
}

export interface Roles {
  company_id: number;
  created_at: Generated<Date | null>;
  description: Generated<string | null>;
  id: Generated<number>;
  is_active: Generated<number | null>;
  name: string;
  public_id: string;
  slug: string;
  updated_at: Generated<Date | null>;
}

export interface SalesItems {
  id: Generated<number>;
  product_id: number;
  quantity: Decimal;
  sale_id: number;
  total_price: Decimal;
  unit_price: Decimal;
}

export interface SalesOrders {
  company_id: number;
  created_at: Generated<Date | null>;
  customer_id: Generated<number | null>;
  date: Date;
  delivery_address: Generated<string | null>;
  id: Generated<number>;
  nfe_emitted_at: Generated<Date | null>;
  public_id: string;
  status: Generated<"cancelled" | "completed" | "invoiced" | "pending" | "separated">;
  total_amount: Generated<Decimal>;
  updated_at: Generated<Date | null>;
}

export interface Suppliers {
  certificate_expiration: Generated<Date | null>;
  certificate_password: Generated<string | null>;
  certificate_url: Generated<string | null>;
  city: Generated<string | null>;
  cnpj_cpf: Generated<string | null>;
  cnpj_document_url: Generated<string | null>;
  company_id: number;
  complement: Generated<string | null>;
  created_at: Generated<Date | null>;
  email: Generated<string | null>;
  id: Generated<number>;
  name: string;
  neighborhood: Generated<string | null>;
  number: Generated<string | null>;
  phone: Generated<string | null>;
  public_id: string;
  social_contract_url: Generated<string | null>;
  state: Generated<string | null>;
  street: Generated<string | null>;
  updated_at: Generated<Date | null>;
  zipcode: Generated<string | null>;
}

export interface TaxRules {
  cbs_percentage: Generated<Decimal>;
  cest: Generated<string | null>;
  cofins_percentage: Generated<Decimal>;
  company_id: number;
  created_at: Generated<Date | null>;
  csosn: Generated<string | null>;
  cst_cbs: Generated<string | null>;
  cst_cofins: Generated<string | null>;
  cst_ibs: Generated<string | null>;
  cst_icms: Generated<string | null>;
  cst_is: Generated<string | null>;
  cst_pis: Generated<string | null>;
  fecp_percentage: Generated<Decimal>;
  ibs_percentage: Generated<Decimal>;
  icms_percentage: Generated<Decimal>;
  icms_type: Generated<string | null>;
  id: Generated<number>;
  ipi_percentage: Generated<Decimal>;
  is_percentage: Generated<Decimal>;
  iss_percentage: Generated<Decimal>;
  mva_internal_percentage: Generated<Decimal | null>;
  mva_interstate_percentage: Generated<Decimal | null>;
  name: string;
  ncm: Generated<string | null>;
  pis_percentage: Generated<Decimal>;
  public_id: string;
  service_code: Generated<string | null>;
  updated_at: Generated<Date | null>;
}

export interface Transactions {
  amount: Decimal;
  bank_account_id: number;
  barcode: Generated<string | null>;
  billet_url: Generated<string | null>;
  category_id: number;
  company_id: number;
  created_at: Generated<Date | null>;
  /**
   * Vinculo com cliente (Receita)
   */
  customer_id: Generated<number | null>;
  date: Date;
  description: string;
  id: Generated<number>;
  /**
   * Forma de Pagamento
   */
  payment_method: Generated<"boleto" | "cash" | "credit" | "debit" | "pix" | "transfer" | null>;
  pix_code: Generated<string | null>;
  public_id: string;
  /**
   * Vinculo com ordem de compra (Despesa)
   */
  purchase_id: Generated<number | null>;
  /**
   * Vinculo com ordem de venda (Receita)
   */
  sale_id: Generated<number | null>;
  status: Generated<"cancelled" | "paid" | "pending">;
  /**
   * Vinculo com fornecedor (Despesa)
   */
  supplier_id: Generated<number | null>;
  type: "expense" | "income";
  updated_at: Generated<Date | null>;
  /**
   * Usuário que registrou a transação
   */
  user_id: number;
}

export interface Users {
  city: Generated<string | null>;
  company_id: number;
  complement: Generated<string | null>;
  cpf_cnpj: Generated<string | null>;
  created_at: Generated<Date | null>;
  email: string;
  full_name: string;
  id: Generated<number>;
  is_active: Generated<number>;
  neighborhood: Generated<string | null>;
  number: Generated<string | null>;
  password_hash: string;
  phone: Generated<string | null>;
  /**
   * UUID for public reference
   */
  public_id: string;
  role: Generated<string>;
  state: Generated<string | null>;
  street: Generated<string | null>;
  updated_at: Generated<Date | null>;
  zipcode: Generated<string | null>;
}

export interface WhatsappBusinessMessages {
  chat_id: Generated<string | null>;
  company_id: number;
  contact_name: Generated<string | null>;
  contact_phone: string;
  created_at: Generated<Date | null>;
  direction: "inbound" | "outbound";
  id: Generated<number>;
  media_base64: Generated<string | null>;
  media_file_name: Generated<string | null>;
  media_mime_type: Generated<string | null>;
  media_url: Generated<string | null>;
  message_id: Generated<string | null>;
  message_text: string;
  message_timestamp: Generated<number | null>;
  message_type: Generated<string | null>;
  owner_id: number;
  owner_type: Generated<"company" | "user">;
  public_id: string;
  raw_payload: Generated<string | null>;
  status: Generated<string | null>;
  updated_at: Generated<Date | null>;
  user_id: Generated<number | null>;
}

export interface WhatsappJobs {
  created_at: Generated<Date | null>;
  error_message: Generated<string | null>;
  id: Generated<number>;
  payload: string;
  processed_at: Generated<Date | null>;
  status: Generated<"completed" | "failed" | "pending" | "processing" | null>;
  type: string;
}

export interface DB {
  accounting_entries: AccountingEntries;
  bank_accounts: BankAccounts;
  bank_statements: BankStatements;
  categories: Categories;
  chart_of_accounts: ChartOfAccounts;
  companies: Companies;
  customers: Customers;
  ibge_cities: IbgeCities;
  ibge_states: IbgeStates;
  inventory_movements: InventoryMovements;
  manufacturers: Manufacturers;
  measures: Measures;
  price_tables: PriceTables;
  product_categories: ProductCategories;
  products: Products;
  purchase_items: PurchaseItems;
  purchase_orders: PurchaseOrders;
  role_permissions: RolePermissions;
  roles: Roles;
  sales_items: SalesItems;
  sales_orders: SalesOrders;
  suppliers: Suppliers;
  tax_rules: TaxRules;
  transactions: Transactions;
  users: Users;
  whatsapp_business_messages: WhatsappBusinessMessages;
  whatsapp_jobs: WhatsappJobs;
}
